version: "0.0.1"

networks:
  app-net:
    driver: bridge

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - app-net

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net

  backend:
    build: .
    container_name: backend
    command: python application.py --stack backend
    restart: always
    env_file:
      - backend/config/backend.env
    ports:
      - 5001:5001
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      - app-net

  frontend:
    build: .
    container_name: frontend
    command: python application.py --stack frontend
    restart: always
    env_file:
      - frontend/config/frontend.env
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - backend
    networks:
      - app-net